a = input('Digite um número')
print(type(a))
n = float(input('Digite um número inteiro: '))
print(n)
s =bool(input('Digite qualquer coisa ou deixe em branco '))
print(s)
e = input('Digite qualquer coisa')
print(e.isalpha())
f = input('Digite números ou letras')
print (f.isnumeric())
